2024-03-01 16:21:37,283 [WARNING]: Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc27891d350>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:21:37,293 [WARNING]: Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc2787738d0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:21:37,304 [WARNING]: Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc27877cf90>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:21:37,313 [WARNING]: Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc278773650>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:21:37,322 [WARNING]: Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc278771190>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:22:33,720 [WARNING]: Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d6a590>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:22:33,730 [WARNING]: Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d6be50>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:22:33,740 [WARNING]: Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d6bd10>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:22:33,750 [WARNING]: Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d6a090>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:22:33,758 [WARNING]: Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc278771310>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:23:06,791 [WARNING]: Compute Engine Metadata server unavailable on attempt 1 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d6f4d0>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:23:06,800 [WARNING]: Compute Engine Metadata server unavailable on attempt 2 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d80b10>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:23:06,811 [WARNING]: Compute Engine Metadata server unavailable on attempt 3 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d82110>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:23:06,822 [WARNING]: Compute Engine Metadata server unavailable on attempt 4 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d6ed10>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
2024-03-01 16:23:06,856 [WARNING]: Compute Engine Metadata server unavailable on attempt 5 of 5. Reason: HTTPConnectionPool(host='metadata.google.internal', port=80): Max retries exceeded with url: /computeMetadata/v1/instance/service-accounts/default/?recursive=true (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7fc277d6ea90>: Failed to resolve 'metadata.google.internal' ([Errno -2] Name or service not known)"))
